version: '3.6'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=department
      - POSTGRES_PASSWORD=department
      - POSTGRES_DB=department
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql