server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    username: employee
    url: jdbc:postgresql://localhost:5432/employee
    password: employee
  jpa:
    generate-ddl: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update